package com.pv.cases.model;

import java.time.Instant;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;

/**
 * A question a reviewer raised against one field of a case, stored for human
 * follow-up. There is no answering logic — a query is recorded and returned.
 *
 * <p>{@code id} and {@code createdAt} are server-generated by
 * {@link #create(String, String, String)} and are therefore left unvalidated, so
 * the same record can bind an inbound request body that omits them.
 *
 * @param caseId    the case the question is about
 * @param fieldPath dot-separated section and field, e.g. {@code "patient.age"},
 *                  addressing one entry of {@link CaseDocument#sections()}
 * @param question  the reviewer's question in free text
 */
public record Query(
		String id,
		@JsonProperty("case_id") @NotBlank String caseId,
		@JsonProperty("field_path") @NotBlank @Pattern(
				regexp = "[^.\\s]+\\.[^.\\s]+",
				message = "must be a dot-separated section and field, e.g. patient.age") String fieldPath,
		@NotBlank String question,
		@JsonProperty("created_at") Instant createdAt) {

	/**
	 * Creates a query with a generated identifier and creation timestamp.
	 */
	public static Query create(String caseId, String fieldPath, String question) {
		return new Query(UUID.randomUUID().toString(), caseId, fieldPath, question, Instant.now());
	}

	/**
	 * @return the section half of {@link #fieldPath()}, e.g. {@code "patient"}
	 */
	public String sectionName() {
		return fieldPath.substring(0, fieldPath.indexOf('.'));
	}

	/**
	 * @return the field half of {@link #fieldPath()}, e.g. {@code "age"}
	 */
	public String fieldName() {
		return fieldPath.substring(fieldPath.indexOf('.') + 1);
	}
}
